[View in Colaboratory](https://colab.research.google.com/github/Gteamer/Tensorflow-Practice/blob/master/Basic_Tensorflow_Classification.ipynb)

In [0]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import tensorflow as tf

%matplotlib inline

In [0]:
houses = [{'Area':2104,'Bathrooms': 3,'Label':	'Good'},
{'Area': 1600,	'Bathrooms':3,'Label':	'Good'},
{'Area': 2400,	'Bathrooms':3,'Label':	'Good'},
{'Area': 1416,	'Bathrooms':2,'Label':	'Bad'},
{'Area': 3000,	'Bathrooms':4,'Label':	'Bad'},
{'Area': 1985,	'Bathrooms':4,'Label':	'Good'},
{'Area': 1534,	'Bathrooms':3,'Label':	'Bad'},
{'Area': 1427,	'Bathrooms':3,'Label':	'Good'},
{'Area': 1380,	'Bathrooms':3,'Label':	'Good'},
{'Area': 1494,	'Bathrooms':3,'Label':	'Good'}]

In [0]:
data = pd.DataFrame(houses)

In [83]:
data.head(10)

Area  Bathrooms Label
0  2104          3  Good
1  1600          3  Good
2  2400          3  Good
3  1416          2   Bad
4  3000          4   Bad
5  1985          4  Good
6  1534          3   Bad
7  1427          3  Good
8  1380          3  Good
9  1494          3  Good

In [0]:
data['Y1'] = data['Label'].apply(lambda x: 1 if x == 'Good' else 0)
data['Y2'] = data['Label'].apply(lambda x: 1 if x == 'Bad' else 0)
data.drop('Label',axis=1, inplace=True)

In [85]:
data

Area  Bathrooms  Y1  Y2
0  2104          3   1   0
1  1600          3   1   0
2  2400          3   1   0
3  1416          2   0   1
4  3000          4   0   1
5  1985          4   1   0
6  1534          3   0   1
7  1427          3   1   0
8  1380          3   1   0
9  1494          3   1   0

In [0]:
inputX = data.iloc[:, 0:2].as_matrix()
inputY = data.loc[:, ['Y1', 'Y2']].as_matrix()

In [87]:
inputX

array([[2104,    3],
       [1600,    3],
       [2400,    3],
       [1416,    2],
       [3000,    4],
       [1985,    4],
       [1534,    3],
       [1427,    3],
       [1380,    3],
       [1494,    3]])

In [88]:
inputY

array([[1, 0],
       [1, 0],
       [1, 0],
       [0, 1],
       [0, 1],
       [1, 0],
       [0, 1],
       [1, 0],
       [1, 0],
       [1, 0]])

## Parameters

In [0]:
learning_rate = 0.000001
training_epochs = 2000
display_step = 50
n_samples = inputY.size

In [0]:
x = tf.placeholder(tf.float32, [None, 2]) # This will be an array of area and number of bathrooms

W = tf.Variable(tf.zeros([2,2])) # Maintain a 2 x 2 float matrix for the weights

b = tf.Variable(tf.zeros([2])) # Also maintain 2 bias values

y_values = tf.add(tf.matmul(x, W), b) # Multiply the matrices and then add bias

y = tf.nn.softmax(y_values) # Applying the activation function

y_ = tf.placeholder(tf.float32, [None, 2]) # A matrix of labels for training

### Specifying the Cost Function and using Gradient Descent

In [0]:
cost = tf.reduce_sum(tf.pow(y_ - y, 2))/(2*n_samples) # Cost function, Mean Squared Error

optimizer = tf.train.GradientDescentOptimizer(learning_rate).minimize(cost) # Gradient Descent

## Initialize Variables and Tensorflow Session

In [0]:
init = tf.global_variables_initializer()
sess = tf.Session()
sess.run(init)

In [93]:
for i in range(training_epochs):
  sess.run(optimizer, feed_dict={x: inputX, y_: inputY}) # Take a gradient descent step
  
  if (i) % display_step == 0:
    cc = sess.run(cost, feed_dict={x: inputX, y_: inputY})
    print('Training Step: ', '%04d' % (i), 'cost=', '{:.9f}'.format(cc))
    
    
print('Optimization Finished!')
training_cost = sess.run(cost, feed_dict={x: inputX, y_: inputY})
print("Training cost=", training_cost, "W=", sess.run(W), "b=", sess.run(b), '\n')

Training Step:  0000 cost= 0.114958659
Training Step:  0050 cost= 0.109539941
Training Step:  0100 cost= 0.109539881
Training Step:  0150 cost= 0.109539807
Training Step:  0200 cost= 0.109539740
Training Step:  0250 cost= 0.109539680
Training Step:  0300 cost= 0.109539606
Training Step:  0350 cost= 0.109539531
Training Step:  0400 cost= 0.109539464
Training Step:  0450 cost= 0.109539405
Training Step:  0500 cost= 0.109539323
Training Step:  0550 cost= 0.109539263
Training Step:  0600 cost= 0.109539188
Training Step:  0650 cost= 0.109539129
Training Step:  0700 cost= 0.109539054
Training Step:  0750 cost= 0.109538987
Training Step:  0800 cost= 0.109538913
Training Step:  0850 cost= 0.109538846
Training Step:  0900 cost= 0.109538786
Training Step:  0950 cost= 0.109538712
Training Step:  1000 cost= 0.109538652
Training Step:  1050 cost= 0.109538577
Training Step:  1100 cost= 0.109538510
Training Step:  1150 cost= 0.109538436
Training Step:  1200 cost= 0.109538376
Training Step:  1250 cost

In [94]:
sess.run(y, feed_dict={x: inputX})

array([[0.7112523 , 0.28874776],
       [0.66498977, 0.33501023],
       [0.73657656, 0.26342347],
       [0.64718795, 0.3528121 ],
       [0.78335613, 0.21664387],
       [0.7006948 , 0.2993052 ],
       [0.6586633 , 0.34133673],
       [0.6482863 , 0.35171375],
       [0.6436828 , 0.35631716],
       [0.6548012 , 0.34519887]], dtype=float32)

In [95]:
sess.run(tf.nn.softmax([1., 2.]))

array([0.26894143, 0.7310586 ], dtype=float32)